name: build

on:
  push:
    branches: source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - run: git config --global user.email "731028571@qq.com"
      - run: git config --global user.name "cwj0417"
      - run: sed -i'' "s~git@github.com:cwj0417/fjonas.github.io.git~https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/cwj0417/fjonas.github.io.git~" _config.yml
      - run: npm ci
      - run: hexo d -g
